name: Build and deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli@11

      - name: Deploy to Netlify (CLI)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify deploy --dir=dist --prod --site-id "$NETLIFY_SITE_ID"

      - name: Post-deploy info
        run: |
          echo "Deployed to Netlify site id: ${{ secrets.NETLIFY_SITE_ID }}"
